# Generated by Django 3.1.7 on 2022-11-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutestatus',
            options={'verbose_name': 'Institute Status', 'verbose_name_plural': 'Institute Status'},
        ),
        migrations.AlterModelOptions(
            name='updaterequirementsstatus',
            options={'verbose_name': 'Update Requirements Status', 'verbose_name_plural': 'Update Requirements Status'},
        ),
        migrations.AlterModelOptions(
            name='updatesrequirements',
            options={'verbose_name': 'Institute Status', 'verbose_name_plural': 'Institute Status'},
        ),
    ]
