# Generated by Django 3.1.7 on 2022-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20221104_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatesrequirements',
            options={'verbose_name': 'Institute Requirements', 'verbose_name_plural': 'Institute Requirements'},
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
