# Generated by Django 3.1.7 on 2021-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_uploaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesexecutive',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UploadUser',
        ),
    ]
