# Generated by Django 3.1.7 on 2022-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210915_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesexecutive',
            name='sales_executive_status',
            field=models.CharField(choices=[('Exist SalesExecutive', 'Exist SalesExecutive'), ('Test SalesExecutive', 'Test SalesExecutive'), ('Left SalesExecutive', 'Left SalesExecutive')], default='Exist SalesExecutive', max_length=50, verbose_name='Sales Executive Status'),
        ),
    ]
