# Generated by Django 3.1.7 on 2022-10-04 18:41

from django.db import migrations, models
import django.db.models.deletion
import tech.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210915_1251'),
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_issues', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdevloper', to='membership.techperson')),
            ],
            options={
                'verbose_name': 'Developer Report',
                'verbose_name_plural': 'Developers Report',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=50, null=True)),
                ('task_title', models.CharField(blank=True, max_length=100, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_head', to='membership.techperson')),
                ('project_status', models.ForeignKey(blank=True, default=tech.models.default_status, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pstatus', to='tech.projectstatus')),
                ('workedBy', models.ManyToManyField(blank=True, null=True, related_name='assigned_developers', to='membership.TechPerson')),
            ],
            options={
                'verbose_name': 'Technical User Task',
                'verbose_name_plural': 'Technical Users Task',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskAssignToUser',
        ),
        migrations.AddField(
            model_name='developerreport',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ustatus', to='tech.userstatus'),
        ),
        migrations.AddField(
            model_name='developerreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptask', to='tech.task'),
        ),
        migrations.AddField(
            model_name='developerreport',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tstatus', to='tech.taskstatus'),
        ),
    ]
