# Generated by Django 3.1.7 on 2022-10-11 13:50

from django.db import migrations, models
import django.db.models.deletion
import tech.models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20221004_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerreport',
            name='status',
            field=models.ForeignKey(blank=True, default=tech.models.default_user_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_status', to='tech.userstatus'),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_status', to='tech.taskstatus'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_status',
            field=models.ForeignKey(blank=True, default=tech.models.default_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pstatus', to='tech.projectstatus'),
        ),
    ]
