# Generated by Django 3.1.7 on 2022-10-15 11:26

from django.db import migrations, models
import django.db.models.deletion
import tech.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210915_1251'),
        ('tech', '0003_auto_20221011_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerreport',
            options={'verbose_name': 'Developer Task', 'verbose_name_plural': 'Developers Tasks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_devloper', to='membership.techperson'),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_task', to='tech.task'),
        ),
        migrations.AlterField(
            model_name='developerreport',
            name='task_status',
            field=models.ForeignKey(blank=True, default=tech.models.default_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_status', to='tech.projectstatus'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_status',
            field=models.ForeignKey(blank=True, default=tech.models.default_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_status', to='tech.projectstatus'),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
