# Generated by Django 3.1.6 on 2021-04-15 11:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFeedBack', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 423078, tzinfo=utc))),
                ('rating', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('Cource', models.CharField(blank=True, max_length=200, null=True)),
                ('instituteType', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('callrecording', models.URLField(blank=True, null=True)),
                ('Is_wrongLead', models.BooleanField(default=False)),
                ('nextCallDate', models.DateTimeField(blank=True, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('demoDate', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(max_length=100)),
                ('furtherCall', models.BooleanField()),
                ('priceQuoted', models.CharField(blank=True, default=12000, max_length=200, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_person', to='membership.salesexecutive')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('instituteName', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 420434, tzinfo=utc))),
                ('contactPhone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('numberStudents', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('lead_status', models.CharField(default='is_successfull_lead', max_length=100)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assign', to='membership.salesexecutive')),
                ('workedBy', models.ManyToManyField(blank=True, null=True, related_name='lead_second_assign', to='membership.SalesExecutive')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullyLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceQuoted', models.CharField(max_length=200)),
                ('extra_requirement', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 422405, tzinfo=utc))),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successfull_lead_user', to='membership.salesexecutive')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comfirmed_lead', to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(blank=True, null=True)),
                ('is_FirstTime', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 426683, tzinfo=utc))),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to='membership.salesexecutive')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageSender_name', to='membership.salesexecutive')),
            ],
        ),
        migrations.CreateModel(
            name='Massages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(blank=True, null=True)),
                ('massagRead', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 425821, tzinfo=utc))),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.feedback')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.lead')),
                ('reciverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='membership.salesexecutive')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='membership.salesexecutive')),
            ],
            options={
                'verbose_name': 'Massage',
                'verbose_name_plural': 'Massages',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeback_lead', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='nextCall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_nextcall', to='membership.salesexecutive'),
        ),
        migrations.CreateModel(
            name='DemoFeedback_And_LeadFeedback_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('massage', models.TextField(blank=True, null=True)),
                ('is_FirstTime', models.BooleanField(default=True)),
                ('nextDate', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 427387, tzinfo=utc))),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.lead')),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demofeedbackuser_notification', to='membership.salesexecutive')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DemoAssigner_name', to='membership.salesexecutive')),
            ],
        ),
        migrations.CreateModel(
            name='DemoFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedemo', models.IntegerField()),
                ('demo_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('demo_feedback', models.CharField(max_length=100)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('price_quoted', models.CharField(blank=True, default=12000, max_length=200, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 11, 24, 57, 424624, tzinfo=utc))),
                ('demo_nextCallDate', models.DateTimeField(blank=True, null=True)),
                ('callrecording', models.URLField(blank=True, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_person', to='membership.salesexecutive')),
                ('demo_nextCall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_nextcall', to='membership.salesexecutive')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_lead', to='sales.lead')),
            ],
            options={
                'verbose_name': 'DemoFeedback',
                'verbose_name_plural': 'DemoFeedbacks',
            },
        ),
    ]
