# Generated by Django 3.1.7 on 2021-08-20 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210425_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 186222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 188560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 184822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 181897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 187097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 187857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 11, 17, 40, 183793, tzinfo=utc)),
        ),
    ]
