# Generated by Django 3.1.7 on 2021-08-25 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210820_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='forcheck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 50625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 53116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 49507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 47199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 51533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 52240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 49, 56, 48768, tzinfo=utc)),
        ),
    ]
