# Generated by Django 3.1.7 on 2021-08-25 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210825_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='forcheck',
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 333033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 335585, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 331819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 329699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 334100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 334805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 10, 50, 15, 331186, tzinfo=utc)),
        ),
    ]
