# Generated by Django 3.1.7 on 2021-09-16 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210915_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demofeedback',
            name='callrecording',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 464507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 468595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 463387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 461261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 465334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 467806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 7, 32, 43, 462813, tzinfo=utc)),
        ),
    ]
