# Generated by Django 3.1.7 on 2022-08-19 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210916_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='freeTime',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='numberStudents',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 130968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 133370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 129746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 127605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 131830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 132611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 7, 32, 46, 129157, tzinfo=utc)),
        ),
    ]
