# Generated by Django 3.1.7 on 2022-10-11 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210915_1251'),
        ('sales', '0019_auto_20221007_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 685461)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 687725)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 683975)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 681804)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 686338)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 687052)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 683382)),
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_conversion', models.IntegerField(blank=True)),
                ('total_conversion_amount', models.IntegerField(blank=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 50, 8, 688349))),
                ('sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_user_conversion', to='membership.salesexecutive')),
            ],
        ),
    ]
