# Generated by Django 3.1.7 on 2022-10-12 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20221011_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_this_reassigned_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 567998)),
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 565060)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 567314)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 563676)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 561275)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 565867)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 566549)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 9, 25, 563066)),
        ),
    ]
