# Generated by Django 3.1.7 on 2022-11-04 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20221018_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 184538)),
        ),
        migrations.AlterField(
            model_name='demofeedback',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 181912)),
        ),
        migrations.AlterField(
            model_name='demofeedback_and_leadfeedback_notifications',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 183990)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 180690)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 178749)),
        ),
        migrations.AlterField(
            model_name='massages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 182710)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 183321)),
        ),
        migrations.AlterField(
            model_name='successfullylead',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 16, 20, 180138)),
        ),
    ]
